import sqlite3

conn = sqlite3.connect("sqlite.db")
cur = conn.cursor()

cur.execute(
    "CREATE TABLE LOGIN(ID INT PRIMARY KEY NOT NULL, PROFESSION VARCHAR(30) NOT NULL, USERNAME VARCHAR(30) NOT NULL, PASSWORD VARCHAR(30) NOT NULL)"
)
cur.execute('CREATE TABLE ADMINLOGIN(ID INT PRIMARY KEY NOT NULL, USERNAME VARCHAR(30) NOT NULL, PASSWORD VARCHAR(30) NOT NULL)')


conn.close()
