import sqlite3

conn = sqlite3.connect("sqlite.db")
cur = conn.cursor()

cur.execute(
    "CREATE TABLE DETAILS(ID INT PRIMARY KEY NOT NULL, WARDID TEXT NOT NULL, ROOMNO VARCHAR(10) NOT NULL, IPID INT, NAME INT, AGE INT, SEX INT, MARITALSTATUS INT, STREET TEXT, AREA TEXT, CITY TEXT, STATE TEXT, PINCODE TEXT, PHONENO INT, EMAIL INT, COMPANYID INT, CATEGORYID INT, ADMITTEDON DATE, ADMITTEDBY TEXT, DISCHARGEDATE DATE,DIAGNOSIS TEXT, CONSULTANTNAME TEXT, OTCOMPLAINS TEXT, ACTION_TAKEN TEXT)"
)

conn.close()
