import sqlite3

conn = sqlite3.connect("sqlite.db")
cur = conn.cursor()

# cur.execute("DROP TABLE FEEDBACKFORM")
cur.execute(
    "CREATE TABLE FEEDBACKFORM(ID INTEGER PRIMARY KEY NOT NULL, IPID INT NOT NULL, WARDID TEXT NOT NULL, ROOMNO VARCHAR(10) NOT NULL, DATE_OF_FEEDBACK DATE, SATISFACTION_WITH_DOCTOR TEXT, SATISFACTION_WTIH_NURSE TEXT, W TEXT, MEDICAL_COMPLAINS TEXT, ANY_OTHER_COMPLAINS TEXT, FEEDBACK_TYPE TEXT, REMARKS TEXT)"
)
conn.commit()
conn.close()
